#!/usr/bin/env python3

import rospy
from sensor_msgs.msg import JointState

from markers import *
from funciones import *

rospy.init_node("testForwardKinematics")
pub = rospy.Publisher('joint_states', JointState, queue_size=1)
bmarker = BallMarker(color['GREEN'])

# Joint names
jnames = ['Revolucion1', 'Revolucion2', 'Revolucion3','Revolucion4', 'Revolucion5', 'Revolucion6']
# Joint Configuration
q = [1.2, 0, 0, 0, 0, 1.2]

# End effector with respect to the base
T = fkine_kuka_kr4(q)
print( np.round(T, 3) )
bmarker.position(T)

# Object (message) whose type is JointState
jstate = JointState()
# Set values to the message
jstate.header.stamp = rospy.Time.now()
jstate.name = jnames
# Add the head joint value (with value 0) to the joints
jstate.position = q

# Loop rate (in Hz)
rate = rospy.Rate(20)
# Continuous execution loop
while not rospy.is_shutdown():
    # Current time (needed for ROS)
    jstate.header.stamp = rospy.Time.now()
    # Publish the message
    pub.publish(jstate)
    bmarker.publish()
    # Wait for the next iteration
    rate.sleep()
